In [6]:
import numpy as np
import pandas as pd
from io import StringIO

In [7]:
xml_1="""<catalog>
    <book>
        <id>1</id>
        <author>Cal Newport</author>
        <title>Deep Work</title>
    </book>
</catalog>"""
pd.read_xml(StringIO(xml_1))

   id       author      title
0   1  Cal Newport  Deep Work

In [8]:
xml_2="""<catalog>
    <book id="1" author="Cal Newport" title="Deep Work" />
</catalog>"""
pd.read_xml(StringIO(xml_2),attrs_only=True)

   id       author      title
0   1  Cal Newport  Deep Work

In [9]:
xml_3="""<catalog>
    <book id="1" status="published">
        <author>Cal Newport</author>
        <title>Deep Work</title>
    </book>
</catalog>"""
pd.read_xml(StringIO(xml_3))

   id     status       author      title
0   1  published  Cal Newport  Deep Work