In [1]:
import pandas as pd
import numpy as np
from io import StringIO

In [2]:
book_datj={"Book":"Deep Work",
          "Author":"Cal Newport",
          "Details":{"pages":304,
                      "cover type":"Papertype",
                      "ISBN":9781455586691}
        }

In [6]:
pd.json_normalize(book_datj)

        Book       Author  Details.pages Details.cover type   Details.ISBN
0  Deep Work  Cal Newport            304          Papertype  9781455586691

In [4]:
att_dtj=[{"Section":"A",
        "students":["John","Adam","Rick"],
        "attendance":{"John":"Present",
                      "Adam":"Absent",
                      "Rick":"Absent"}},
        {"Section":"B",
        "students":["Bill","Jane","Kenny"],
        "attendance":
                {"Bill":"Present",
                 "Jane":"Absent",
                 "Kenny":"Present"}},
        {"Section":"C",
        "students":["Walton","Isabel","Lili"],
        "attendance":
                {"Walton":"Present",
                 "Isabel":"Absent",
                 "Lili":"Present"}}]

In [5]:
pd.json_normalize(att_dtj,sep=" of ")

,Section,students,attendance of John,attendance of Adam,attendance of Rick,attendance of Bill,attendance of Jane,attendance of Kenny,attendance of Walton,attendance of Isabel,attendance of Lili
0,A,"[John, Adam, Rick]",Present,Absent,Absent,NaN,NaN,NaN,NaN,NaN,NaN
1,B,"[Bill, Jane, Kenny]",NaN,NaN,NaN,Present,Absent,Present,NaN,NaN,NaN
2,C,"[Walton, Isabel, Lili]",NaN,NaN,NaN,NaN,NaN,NaN,Present,Absent,Present